# frozen_string_literal: true
module Stupidedi
  module Versions
    module FiftyTen

      module SegmentDefs
        autoload :AAA, "stupidedi/versions/005010/segment_defs/AAA"
        autoload :ACT, "stupidedi/versions/005010/segment_defs/ACT"
        autoload :AK1, "stupidedi/versions/005010/segment_defs/AK1"
        autoload :AK2, "stupidedi/versions/005010/segment_defs/AK2"
        autoload :AK9, "stupidedi/versions/005010/segment_defs/AK9"
        autoload :AMT, "stupidedi/versions/005010/segment_defs/AMT"
        autoload :BGN, "stupidedi/versions/005010/segment_defs/BGN"
        autoload :BHT, "stupidedi/versions/005010/segment_defs/BHT"
        autoload :BPR, "stupidedi/versions/005010/segment_defs/BPR"
        autoload :CAS, "stupidedi/versions/005010/segment_defs/CAS"
        autoload :CL1, "stupidedi/versions/005010/segment_defs/CL1"
        autoload :CLM, "stupidedi/versions/005010/segment_defs/CLM"
        autoload :CLP, "stupidedi/versions/005010/segment_defs/CLP"
        autoload :CN1, "stupidedi/versions/005010/segment_defs/CN1"
        autoload :COB, "stupidedi/versions/005010/segment_defs/COB"
        autoload :CR1, "stupidedi/versions/005010/segment_defs/CR1"
        autoload :CR2, "stupidedi/versions/005010/segment_defs/CR2"
        autoload :CR3, "stupidedi/versions/005010/segment_defs/CR3"
        autoload :CRC, "stupidedi/versions/005010/segment_defs/CRC"
        autoload :CTP, "stupidedi/versions/005010/segment_defs/CTP"
        autoload :CTX, "stupidedi/versions/005010/segment_defs/CTX"
        autoload :CUR, "stupidedi/versions/005010/segment_defs/CUR"
        autoload :DMG, "stupidedi/versions/005010/segment_defs/DMG"
        autoload :DN1, "stupidedi/versions/005010/segment_defs/DN1"
        autoload :DN2, "stupidedi/versions/005010/segment_defs/DN2"
        autoload :DSB, "stupidedi/versions/005010/segment_defs/DSB"
        autoload :DTM, "stupidedi/versions/005010/segment_defs/DTM"
        autoload :DTP, "stupidedi/versions/005010/segment_defs/DTP"
        autoload :EB,  "stupidedi/versions/005010/segment_defs/EB"
        autoload :EC,  "stupidedi/versions/005010/segment_defs/EC"
        autoload :EQ,  "stupidedi/versions/005010/segment_defs/EQ"
        autoload :FRM, "stupidedi/versions/005010/segment_defs/FRM"
        autoload :GE,  "stupidedi/versions/005010/segment_defs/GE"
        autoload :GS,  "stupidedi/versions/005010/segment_defs/GS"
        autoload :HCP, "stupidedi/versions/005010/segment_defs/HCP"
        autoload :HD,  "stupidedi/versions/005010/segment_defs/HD"
        autoload :HI,  "stupidedi/versions/005010/segment_defs/HI"
        autoload :HL,  "stupidedi/versions/005010/segment_defs/HL"
        autoload :HLH, "stupidedi/versions/005010/segment_defs/HLH"
        autoload :HSD, "stupidedi/versions/005010/segment_defs/HSD"
        autoload :ICM, "stupidedi/versions/005010/segment_defs/ICM"
        autoload :IDC, "stupidedi/versions/005010/segment_defs/IDC"
        autoload :III, "stupidedi/versions/005010/segment_defs/III"  
        autoload :IK3, "stupidedi/versions/005010/segment_defs/IK3"
        autoload :IK4, "stupidedi/versions/005010/segment_defs/IK4"
        autoload :IK5, "stupidedi/versions/005010/segment_defs/IK5"
        autoload :INS, "stupidedi/versions/005010/segment_defs/INS"
        autoload :K3,  "stupidedi/versions/005010/segment_defs/K3"
        autoload :LE,  "stupidedi/versions/005010/segment_defs/LE"
        autoload :LE,  "stupidedi/versions/005010/segment_defs/LE"
        autoload :LIN, "stupidedi/versions/005010/segment_defs/LIN"
        autoload :LQ,  "stupidedi/versions/005010/segment_defs/LQ"
        autoload :LS,  "stupidedi/versions/005010/segment_defs/LS"
        autoload :LUI, "stupidedi/versions/005010/segment_defs/LUI"
        autoload :LX,  "stupidedi/versions/005010/segment_defs/LX"
        autoload :MEA, "stupidedi/versions/005010/segment_defs/MEA"
        autoload :MIA, "stupidedi/versions/005010/segment_defs/MIA"
        autoload :MOA, "stupidedi/versions/005010/segment_defs/MOA"
        autoload :MPI, "stupidedi/versions/005010/segment_defs/MPI"
        autoload :MSG, "stupidedi/versions/005010/segment_defs/MSG"
        autoload :N1,  "stupidedi/versions/005010/segment_defs/N1"
        autoload :N2,  "stupidedi/versions/005010/segment_defs/N2"
        autoload :N3,  "stupidedi/versions/005010/segment_defs/N3"
        autoload :N4,  "stupidedi/versions/005010/segment_defs/N4"
        autoload :NM1, "stupidedi/versions/005010/segment_defs/NM1"
        autoload :NTE, "stupidedi/versions/005010/segment_defs/NTE"
        autoload :OI,  "stupidedi/versions/005010/segment_defs/OI"
        autoload :PAT, "stupidedi/versions/005010/segment_defs/PAT"
        autoload :PER, "stupidedi/versions/005010/segment_defs/PER"
        autoload :PLA, "stupidedi/versions/005010/segment_defs/PLA"
        autoload :PLB, "stupidedi/versions/005010/segment_defs/PLB"
        autoload :PRV, "stupidedi/versions/005010/segment_defs/PRV"
        autoload :PS1, "stupidedi/versions/005010/segment_defs/PS1"
        autoload :PWK, "stupidedi/versions/005010/segment_defs/PWK"
        autoload :QTY, "stupidedi/versions/005010/segment_defs/QTY"
        autoload :RDM, "stupidedi/versions/005010/segment_defs/RDM"
        autoload :REF, "stupidedi/versions/005010/segment_defs/REF"
        autoload :SBR, "stupidedi/versions/005010/segment_defs/SBR"
        autoload :SE,  "stupidedi/versions/005010/segment_defs/SE"
        autoload :ST,  "stupidedi/versions/005010/segment_defs/ST"
        autoload :STC, "stupidedi/versions/005010/segment_defs/STC"
        autoload :SV1, "stupidedi/versions/005010/segment_defs/SV1"
        autoload :SV2, "stupidedi/versions/005010/segment_defs/SV2"
        autoload :SV3, "stupidedi/versions/005010/segment_defs/SV3"
        autoload :SV5, "stupidedi/versions/005010/segment_defs/SV5"
        autoload :SVC, "stupidedi/versions/005010/segment_defs/SVC"
        autoload :SVD, "stupidedi/versions/005010/segment_defs/SVD"
        autoload :TOO, "stupidedi/versions/005010/segment_defs/TOO"
        autoload :TRN, "stupidedi/versions/005010/segment_defs/TRN"
        autoload :TS2, "stupidedi/versions/005010/segment_defs/TS2"
        autoload :TS3, "stupidedi/versions/005010/segment_defs/TS3"
      end

    end
  end
end
