module Stupidedi
  module Guides
    module FiftyTen
      module X222

        d = Schema
        e = Envelope
        r = Dictionaries::FunctionalGroups::FiftyTen::SegmentReqs
        s = Dictionaries::FunctionalGroups::FiftyTen::SegmentDefs

        HC837 = e::TransactionSetDef.build("HC", "837",

          d::TableDef.build("Table 1 - Header",
            s::BHT.use(100, r::Mandatory, d::RepeatCount.bounded(1)),

            d::LoopDef.build("1000A SUBMITTER NAME", d::RepeatCount.bounded(1),
              s::NM1.use(200, r::Mandatory, d::RepeatCount.bounded(1)),
              s::PER.use(450, r::Mandatory, d::RepeatCount.bounded(2))),

            d::LoopDef.build("1000B RECEIVER NAME", d::RepeatCount.bounded(1),
              s::NM1.use(200, r::Mandatory, d::RepeatCount.bounded(1)))),

          d::TableDef.build("Table 2 - Billing Provider Detail",
            d::LoopDef.build("2000A BILLING PROVIDER HIERARCHICAL LEVEL", d::RepeatCount.unbounded,
              s:: HL.use( 10, r::Mandatory, d::RepeatCount.bounded(1)),
              s::PRV.use( 30, r::Optional,  d::RepeatCount.bounded(1)),
              s::CUR.use(100, r::Optional,  d::RepeatCount.bounded(1)),

              d::LoopDef.build("2010AA BILLING PROVIDER NAME", d::RepeatCount.bounded(1),
                s::NM1.use(150, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: N4.use(300, r::Mandatory, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Mandatory, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Optional,  d::RepeatCount.bounded(2)),
                s::PER.use(400, r::Optional,  d::RepeatCount.bounded(2))),

              d::LoopDef.build("2010AB PAY-TO ADDRESS NAME", d::RepeatCount.bounded(1),
                s::NM1.use(150, r::Optional,  d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: N4.use(300, r::Mandatory, d::RepeatCount.bounded(1))),

              d::LoopDef.build("2010AC PAY-TO PLAN NAME", d::RepeatCount.bounded(1),
                s::NM1.use(150, r::Optional,  d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: N4.use(300, r::Mandatory, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Mandatory, d::RepeatCount.bounded(1))))),

          d::TableDef.build("Table 2 - Subscriber Detail",
            d::LoopDef.build("2000B SUBSCRIBER HIERARCHICAL LEVEL", d::RepeatCount.unbounded,
              s:: HL.use( 10, r::Mandatory, d::RepeatCount.bounded(1)),
              s::SBR.use( 50, r::Optional,  d::RepeatCount.bounded(1)),
              s::PAT.use( 70, r::Optional,  d::RepeatCount.bounded(1)),

              d::LoopDef.build("2010BA SUBSCRIBER NAME", d::RepeatCount.bounded(1),
                s::NM1.use(150, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Optional,  d::RepeatCount.bounded(1)),
                s:: N4.use(300, r::Mandatory, d::RepeatCount.bounded(1)),
                s::DMG.use(320, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Optional,  d::RepeatCount.bounded(1)),
                s::PER.use(400, r::Optional,  d::RepeatCount.bounded(1))),

              d::LoopDef.build("2010BB PAYER NAME", d::RepeatCount.bounded(10),
                s::NM1.use(150, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Optional,  d::RepeatCount.bounded(2)),
                s:: N4.use(300, r::Mandatory, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Optional,  d::RepeatCount.bounded(3)),
                s::REF.use(350, r::Optional,  d::RepeatCount.bounded(2))))),

          d::TableDef.build("Table 2 - Patient Detail",
            d::LoopDef.build("2000 PATIENT HIERARCHICAL LEVEL", d::RepeatCount.unbounded,
              s:: HL.use( 10, r::Optional,  d::RepeatCount.bounded(1)),
              s::PAT.use( 70, r::Mandatory, d::RepeatCount.bounded(1)),

              d::LoopDef.build("2010CA PATIENT NAME", d::RepeatCount.bounded(1),
                s::NM1.use(150, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: N4.use(300, r::Mandatory, d::RepeatCount.bounded(1)),
                s::DMG.use(320, r::Mandatory, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Optional,  d::RepeatCount.bounded(1)),
                s::PER.use(400, r::Optional,  d::RepeatCount.bounded(1))),

              d::LoopDef.build("2300 CLAIM INFORMATION", d::RepeatCount.bounded(100),
                s::CLM.use(1300, r::Mandatory, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(2)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Optional,  d::RepeatCount.bounded(1)),
                s::PWK.use(1550, r::Optional,  d::RepeatCount.bounded(10)),
                s::CN1.use(1600, r::Optional,  d::RepeatCount.bounded(1)),
                s::AMT.use(1750, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Optional,  d::RepeatCount.bounded(1)),
                s:: K3.use(1850, r::Optional,  d::RepeatCount.bounded(10)),
                s::NTE.use(1900, r::Optional,  d::RepeatCount.bounded(1)),
                s::CR1.use(1950, r::Optional,  d::RepeatCount.bounded(1)),
                s::CR2.use(2000, r::Optional,  d::RepeatCount.bounded(1)),
                s::CRC.use(2200, r::Optional,  d::RepeatCount.bounded(3)),
                s::CRC.use(2200, r::Optional,  d::RepeatCount.bounded(3)),
                s::CRC.use(2200, r::Optional,  d::RepeatCount.bounded(1)),
                s::CRC.use(2200, r::Optional,  d::RepeatCount.bounded(1)),
                s:: HI.use(2310, r::Mandatory, d::RepeatCount.bounded(1)),
                s:: HI.use(2310, r::Optional,  d::RepeatCount.bounded(1)),
                s:: HI.use(2310, r::Optional,  d::RepeatCount.bounded(1)),
                s::HCP.use(2410, r::Optional,  d::RepeatCount.bounded(1)),

                d::LoopDef.build("2310A REFERRING PROVIDER NAME", d::RepeatCount.bounded(2),
                  s::NM1.use(2500, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(2710, r::Optional,  d::RepeatCount.bounded(3))),

                d::LoopDef.build("2310B RENDERING PROVIDER NAME", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Optional,  d::RepeatCount.bounded(1)),
                  s::PRV.use(2550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(2710, r::Optional,  d::RepeatCount.bounded(4))),

                d::LoopDef.build("2310C SERVICE FACILITY LOCATION NAME", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Optional,  d::RepeatCount.bounded(1)),
                  s:: N3.use(2650, r::Mandatory, d::RepeatCount.bounded(2)),
                  s:: N4.use(2700, r::Mandatory, d::RepeatCount.bounded(1)),
                  s::REF.use(2710, r::Optional,  d::RepeatCount.bounded(3)),
                  s::PER.use(2750, r::Optional,  d::RepeatCount.bounded(1))),

                d::LoopDef.build("2310D SUPERVISING PROVIDER NAME", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(2710, r::Optional,  d::RepeatCount.bounded(4))),

                d::LoopDef.build("2310E AMBULANCE DROP-OFF LOCATION", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Optional,  d::RepeatCount.bounded(1)),
                  s:: N3.use(2650, r::Optional,  d::RepeatCount.bounded(2)),
                  s:: N4.use(2700, r::Optional,  d::RepeatCount.bounded(1))),

                d::LoopDef.build("2310F AMBULANCE DROP-OFF LOCATION", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Optional,  d::RepeatCount.bounded(1)),
                  s:: N3.use(2650, r::Optional,  d::RepeatCount.bounded(1)),
                  s:: N4.use(2700, r::Optional,  d::RepeatCount.bounded(1))),

                d::LoopDef.build("2320 OTHER SUBSCRIBER INFORMATION", d::RepeatCount.bounded(10),
                  s::SBR.use(2900, r::Optional,  d::RepeatCount.bounded(1)),
                  s::CAS.use(2950, r::Optional,  d::RepeatCount.bounded(5)),
                  s::AMT.use(3000, r::Optional,  d::RepeatCount.bounded(1)),
                  s::AMT.use(3000, r::Optional,  d::RepeatCount.bounded(1)),
                  s::AMT.use(3000, r::Optional,  d::RepeatCount.bounded(1)),
                  s:: OI.use(3100, r::Mandatory, d::RepeatCount.bounded(1)),
                  s::MOA.use(3200, r::Optional,  d::RepeatCount.bounded(1)),

                  d::LoopDef.build("2330A OTHER SUBSCRIBER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Mandatory, d::RepeatCount.bounded(1)),
                    s:: N3.use(3320, r::Optional,  d::RepeatCount.bounded(1)),
                    s:: N4.use(3400, r::Mandatory, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Optional,  d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2330B OTHER PAYER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Mandatory, d::RepeatCount.bounded(1)),
                    s:: N3.use(3320, r::Optional,  d::RepeatCount.bounded(1)),
                    s:: N4.use(3400, r::Mandatory, d::RepeatCount.bounded(1)),
                    s::DTP.use(3500, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Optional,  d::RepeatCount.bounded(2)),
                    s::REF.use(3550, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Optional,  d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2330C OTHER PAYER REFERRING PROVIDER", d::RepeatCount.bounded(2),
                    s::NM1.use(3250, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Mandatory, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2330D OTHER PAYER RENDERING PROVIDER", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Mandatory, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2330E OTHER PAYER SERVICE FACILITY LOCATION", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Mandatory, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2330F OTHER PAYER SUPERVISING PROVIDER", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Mandatory, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2330G OTHER PAYER BILLING PROVIDER", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Mandatory, d::RepeatCount.bounded(2)))),

                d::LoopDef.build("2400", d::RepeatCount.bounded(50),
                  s:: LX.use(3650, r::Mandatory, d::RepeatCount.bounded(1)),
                  s::SV1.use(3700, r::Mandatory, d::RepeatCount.bounded(1)),
                  s::SV5.use(4000, r::Optional,  d::RepeatCount.bounded(1)),
                  s::PWK.use(4200, r::Optional,  d::RepeatCount.bounded(10)),
                  s::PWK.use(4200, r::Optional,  d::RepeatCount.bounded(1)),
                  s::CR1.use(4250, r::Optional,  d::RepeatCount.bounded(1)),
                  s::CR3.use(4350, r::Optional,  d::RepeatCount.bounded(1)),
                  s::CRC.use(4500, r::Optional,  d::RepeatCount.bounded(3)),
                  s::CRC.use(4500, r::Optional,  d::RepeatCount.bounded(1)),
                  s::CRC.use(4500, r::Optional,  d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Mandatory, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(2)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Optional,  d::RepeatCount.bounded(1)),
                  s::QTY.use(4600, r::Optional,  d::RepeatCount.bounded(1)),
                  s::QTY.use(4600, r::Optional,  d::RepeatCount.bounded(1)),
                  s::MEA.use(4620, r::Optional,  d::RepeatCount.bounded(5)),
                  s::CN1.use(4650, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(5)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Optional,  d::RepeatCount.bounded(5)),
                  s::AMT.use(4750, r::Optional,  d::RepeatCount.bounded(1)),
                  s::AMT.use(4750, r::Optional,  d::RepeatCount.bounded(1)),
                  s:: K3.use(4800, r::Optional,  d::RepeatCount.bounded(10)),
                  s::NTE.use(4850, r::Optional,  d::RepeatCount.bounded(1)),
                  s::NTE.use(4850, r::Optional,  d::RepeatCount.bounded(1)),
                  s::PS1.use(4880, r::Optional,  d::RepeatCount.bounded(1)),
                  s::HCP.use(4920, r::Optional,  d::RepeatCount.bounded(1)),

                  d::LoopDef.build("2410 DRUG IDENTIFICATION", d::RepeatCount.bounded(1),
                    s::LIN.use(4930, r::Optional,  d::RepeatCount.bounded(1)),
                    s::CTP.use(4940, r::Mandatory, d::RepeatCount.bounded(1)),
                    s::REF.use(4950, r::Optional,  d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2420A RENDERING PROVIDER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Optional,  d::RepeatCount.bounded(1)),
                    s::PRV.use(5050, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Optional,  d::RepeatCount.bounded(20))),

                  d::LoopDef.build("2420B PURCHASED SERVICE PROVIDER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Optional,  d::RepeatCount.bounded(20))),

                  d::LoopDef.build("2420C SERVICE FACILITY LOCATION NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Optional,  d::RepeatCount.bounded(1)),
                    s:: N3.use(5140, r::Mandatory, d::RepeatCount.bounded(1)),
                    s:: N4.use(5200, r::Mandatory, d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Optional,  d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2420D SUPERVISING PROVIDER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Optional,  d::RepeatCount.bounded(20))),

                  d::LoopDef.build("2420E ORDERING PROVIDER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Optional,  d::RepeatCount.bounded(1)),
                    s:: N3.use(5140, r::Optional,  d::RepeatCount.bounded(1)),
                    s:: N4.use(5200, r::Mandatory, d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Optional,  d::RepeatCount.bounded(20)),
                    s::PER.use(5300, r::Optional,  d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2420F REFERRING PROVIDER NAME", d::RepeatCount.bounded(2),
                    s::NM1.use(5000, r::Optional,  d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Optional,  d::RepeatCount.bounded(20))),

                  d::LoopDef.build("2420G AMBULANCE PICK-UP LOCATION", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Optional,  d::RepeatCount.bounded(1)),
                    s:: N3.use(5140, r::Mandatory, d::RepeatCount.bounded(1)),
                    s:: N4.use(5200, r::Mandatory, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2420H AMBULANCE DROP-OFF LOCATION", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Optional,  d::RepeatCount.bounded(1)),
                    s:: N3.use(5140, r::Mandatory, d::RepeatCount.bounded(1)),
                    s:: N4.use(5200, r::Mandatory, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2430 LINE ADJUDICATION INFORMATION", d::RepeatCount.bounded(15),
                    s::SVD.use(5400, r::Optional,  d::RepeatCount.bounded(1)),
                    s::CAS.use(5450, r::Optional,  d::RepeatCount.bounded(5)),
                    s::DTP.use(5500, r::Mandatory, d::RepeatCount.bounded(1)),
                    s::AMT.use(5505, r::Optional,  d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2440", d::RepeatCount.unbounded,
                    s:: LQ.use(5510, r::Optional,  d::RepeatCount.bounded(1)),
                    s::FRM.use(5520, r::Mandatory, d::RepeatCount.bounded(99))))))))

      end
    end
  end
end
