module Stupidedi
  module Guides
    module FiftyTen
      module X222

        d = Schema
        v = Envelope
        r = SegmentReqs
        e = ElementReqs
        s = Dictionaries::FunctionalGroups::FiftyTen::SegmentDefs
        t = Dictionaries::FunctionalGroups::FiftyTen::TransactionSetDefs

        def segment(position, segment_def, requirement, repeat_count, *elements)
        end

        def element(requirement, name, *args)
        end

        HC837 = v::ImplementationGuide.build(t::HC837,

          d::TableDef.build("Table 1 - Header",
            segment(50, s::ST, "Transaction Set Header",
              r::Required, d::RepeatCount.bounded(1),
              element(e::Required,    "Transaction Set Identifier Code"),
              element(e::Required,    "Transaction Set Control Number"),
              element(e::Required,    "Implementation Guide Version Name")),
            segment(100, s::BHT, "Beginning of Hierarchical Transaction",
              r::Required, d::RepeatCount.bounded(1),
              element(e::Required,    "Hierarchical Structure Code", Codes("0019")),
              element(e::Required,    "Transaction Set Purpose Code", Codes("00", "18")),
              element(e::Required,    "Originator Application Transaction Identifier", MaxLength(30)),
              element(e::Required,    "Transaction Set Creation Date"),
              element(e::Required,    "Transaction Set Creation Time"),
              element(e::Required,    "Claim or Encounter Identifier", Codes("31", "CH", "RP"))),

            d::LoopDef.build("1000A SUBMITTER NAME", d::RepeatCount.bounded(1),
              segment(200, s::NM1, "Submitter Name",
                r::Required, d::RepeatCount.bounded(1),
                element(e::Required,    "Entity Identifier Code", Codes("41")),
                element(e::Required,    "Entity Type Qualifier", Codes("1", "2"))),
                element(e::Required,    "Submitter Last or Organization Name"),
                element(e::Situational, "Submitter First Name"),
                element(e::Situational, "Submitter Middle Name or Initial"),
                element(e::NotUsed,     "Name Prefix"),
                element(e::NotUsed,     "Name Suffix"),
                element(e::Required,    "Identification Qualifier Code", Codes("46")),
                element(e::Required,    "Submitter Identifier"),
                element(e::NotUsed,     "Entity Relationship Code"),
                element(e::NotUsed,     "Entity Identifier Code"),
                element(e::NotUsed,     "Name Last or Organization Name"),
              segment(450, s::PER, "Submitter EDI Contact Information",
                r::Required, d::RepeatCount.bounded(2),
                element(e::Required,    "Contact Function Code", Codes("IC")),
                element(e::Situational, "Submitter Contact Name"),
                element(e::Required,    "Communication Number Qualifier", Codes("EM", "FX", "TE")),
                element(e::Required,    "Communication Number"),
                element(e::Situational, "Communication Number Qualifier", Codes("EM", "EX", "FX", "TE")),
                element(e::Situational, "Communication Number"),
                element(e::Situational, "Communication Number Qualifier", Codes("EM", "EX", "FX", "TE")),
                element(e::Situational, "Communication Number"),
                element(e::NotUsed,     "Contact Inquiry Reference"))),

            d::LoopDef.build("1000B RECEIVER NAME", d::RepeatCount.bounded(1),
              segment(200, s::NM1, "Receiver Name",
                r::Required, d::RepeatCount.bounded(1),
                element(e::Required,    "Entity Identifier Code", Codes("40")),
                element(e::Required,    "Entity Type Qualifier", Codes("2")),
                element(e::Required,    "Receiver Name"),
                element(e::NotUsed,     "Name First"),
                element(e::NotUsed,     "Name Last"),
                element(e::NotUsed,     "Name Prefix"),
                element(e::NotUsed,     "Name Suffix"),
                element(e::Required,    "Identification Code Qualifier", Codes("46")),
                element(e::Required,    "Receiver Primary Identifier"),
                element(e::NotUsed,     "Entity Relationship Code"),
                element(e::NotUsed,     "Entity Identifier Code"),
                element(e::NotUsed,     "Name Last or Organization Name")))),

          d::TableDef.build("Table 2 - Billing Provider Detail",
            d::LoopDef.build("2000A BILLING PROVIDER HIERARCHICAL LEVEL", d::RepeatCount.unbounded,
              segment(10, s::HL, "Billing Provider Hierarchical Level",
                r::Required, d::RepeatCount.bounded(1),
                element(e::Required,    "Hierarchical ID Number"),
                element(e::NotUsed,     "Hierarchical Parent ID Number"),
                element(e::Required,    "Hierarchical Level Code", Codes("20")),
                element(e::Required,    "Hierachical Child Code")),
              segment(30, s::PRV, "Billing Provider Specialty Information",
                r::Situational, d::RepeatCount.bounded(1),
                element(e::Required,    "Provider Code", Codes("BI")),
                element(e::Required,    "Reference Identification Number", Codes("PXC")),
                element(e::Required,    "Provider Taxonomy Code"),
                element(e::NotUsed,     "State or Province Code"),
                element(e::NotUsed,     "PROVIDER SPECIALTY INFORMATION"),
                element(e::NotUsed,     "Provider Organization Code")),
              segment(100, s::CUR, "Foreign Currency Information",
                r::Situational, d::RepeatCount.bounded(1),
                element(e::Required,    "Entity Identifier Code", Codes("85")),
                element(e::Required,    "Currency Code"),
                element(e::NotUsed,     "Exchange Rate"),
                element(e::NotUsed,     "Entity Identifier Code"),
                element(e::NotUsed,     "Currency Code"),
                element(e::NotUsed,     "Currency Market/Exchange Code"),
                element(e::NotUsed,     "Date/Time Qualifier"),
                element(e::NotUsed,     "Date"),
                element(e::NotUsed,     "Time"),
                element(e::NotUsed,     "Date/Time Qualifier"),
                element(e::NotUsed,     "Date"),
                element(e::NotUsed,     "Time"),
                element(e::NotUsed,     "Date/Time Qualifier"),
                element(e::NotUsed,     "Date"),
                element(e::NotUsed,     "Time"),
                element(e::NotUsed,     "Date/Time Qualifier"),
                element(e::NotUsed,     "Date"),
                element(e::NotUsed,     "Time"),
                element(e::NotUsed,     "Date/Time Qualifier"),
                element(e::NotUsed,     "Date"),
                element(e::NotUsed,     "Time")),

              d::LoopDef.build("2010AA BILLING PROVIDER NAME", d::RepeatCount.bounded(1),
                segment(150, s::NM1, "Billing Provider Name",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Entity Identifier Code", Codes("85")),
                  element(e::Required,    "Entity Type Qualifier", Codes("1", "2")),
                  element(e::Required,    "Billing Provider Last or Organizational Name"),
                  element(e::Situational, "Billing Provider First Name"),
                  element(e::Situational, "Billing Provider Middle Name or Initial"),
                  element(e::NotUsed,     "Name Prefix"),
                  element(e::Situational, "Billing Provider Name Suffix"),
                  element(e::Situational, "Identification Code Qualifier", Codes("XX")),
                  element(e::Situational, "Billing Provider Identifier"),
                  element(e::NotUsed,     "Entity Relationship Code"),
                  element(e::NotUsed,     "Entity Identifier Code"),
                  element(e::NotUsed,     "Name Last or Organization Name")),
                segment(250, s::N3, "Billing Provider Address",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Billing Provider Address Line"),
                  element(e::Situational, "Billing Provider Address Line")),
                segment(300, s::N4, "Billing Provider City, State, ZIP Code",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Billing Provider City Name"),
                  element(e::Situational, "Billing Provider State or Province Code"),
                  element(e::Situational, "Billing Provider Postal Zone or ZIP Code"),
                  element(e::Situational, "Country Code"),
                  element(e::NotUsed,     "Location Qualifier"),
                  element(e::NotUsed,     "Location Identifier"),
                  element(e::Situational, "Country Subdivision Code")),
                segment(350, s::REF, "Billing Provider Tax Identification",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Reference Identification Qualifier", Codes("EI", "SY")),
                  element(e::Required,    "Billing Provider Tax Identification Number"),
                  element(e::NotUsed,     "Description"),
                  element(e::NotUsed,     "REFERENCE IDENTIFIER")),
                segment(350, s::REF, "Billing Provider UPIN/License Information",
                  r::Situational, d::RepeatCount.bounded(2),
                  element(e::Required,    "Reference Identification Qualifier", Codes("0B", "1G")),
                  element(e::Required,    "Billing Provider License and/or UPIN Information"),
                  element(e::NotUsed,     "Description"),
                  element(e::NotUsed,     "REFERENCE IDENTIFIER")),
                segment(400, s::PER, "Billing Provider Contact Information",
                  r::Situational, d::RepeatCount.bounded(2),
                  element(e::Required,    "Contact Function Code", Codes("IC")),
                  element(e::Situational, "Billing Provider Contact Name"),
                  element(e::Required,    "Communication Number Qualifier", Codes("EM", "FX", "TE")),
                  element(e::Required,    "Communication Number"),
                  element(e::Situational, "Communication Number Qualifier", Codes("EM", "EX", "FX", "TE")),
                  element(e::Situational, "Communication Number"),
                  element(e::Situational, "Communication Number Qualifier", Codes("EM", "EX", "FX", "TE")),
                  element(e::Situational, "Communication Number"),
                  element(e::NotUsed,     "Contact Inquiry Reference"))),

              d::LoopDef.build("2010AB PAY-TO ADDRESS NAME", d::RepeatCount.bounded(1),
                segment(150, s::NM1, "Pay-to Address Name",
                  r::Situational, d::RepeatCount.bounded(1),
                  element(e::Required,    "Entity Identifier Code", Codes("87")),
                  element(e::Required,    "Entity Type Qualifier", Codes("1", "2")),
                  element(e::NotUsed,     "Name Last or Organizational Name"),
                  element(e::NotUsed,     "Name First"),
                  element(e::NotUsed,     "Name Middle"),
                  element(e::NotUsed,     "Name Prefix"),
                  element(e::NotUsed,     "Name Suffix"),
                  element(e::NotUsed,     "Identification Code Qualifier"),
                  element(e::NotUsed,     "Identifier Code"),
                  element(e::NotUsed,     "Entity Relationship Code"),
                  element(e::NotUsed,     "Entity Identifier Code"),
                  element(e::NotUsed,     "Name Last or Organization Name")),
                segment(250, s::N3, "Pay-to Address - ADDRESS",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Pay-To Address Line"),
                  element(e::Situational, "Pay-To Address Line")),
                segment(300, s::N4, "Pay-To Address City, State, "ZIP Code",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Pay-to City Name"),
                  element(e::Situational, "Pay-to State or Province Code"),
                  element(e::Situational, "Pay-to Postal Zone or ZIP Code"),
                  element(e::Situational, "Country Code"),
                  element(e::NotUsed,     "Location Qualifier"),
                  element(e::NotUsed,     "Location Identifier"),
                  element(e::Situational, "Country Subdivision Code"))),

              d::LoopDef.build("2010AC PAY-TO PLAN NAME", d::RepeatCount.bounded(1),
                segment(150, s::NM1, "Pay-To Plan Name",
                  r::Situational, d::RepeatCount.bounded(1),
                  element(e::Required,    "Entity Identifier Code", Codes("PE")),
                  element(e::Required,    "Entity Type Qualifier", Codes("2")),
                  element(e::Required,    "Pay-To Plan Organizational Name"),
                  element(e::NotUsed,     "Name First"),
                  element(e::NotUsed,     "Name Middle"),
                  element(e::NotUsed,     "Name Prefix"),
                  element(e::NotUsed,     "Name Suffix"),
                  element(e::Required,    "Identification Code Qualifier", Codes("PI", "XV")),
                  element(e::Required,    "Pay-To Plan Primary Identifier"),
                  element(e::NotUsed,     "Entity Relationship Code"),
                  element(e::NotUsed,     "Entity Identifier Code"),
                  element(e::NotUsed,     "Name Last or Organization Name")),
                segment(250, s::N3, "Pay-to Plan Address",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Pay-To Plan Address Line"),
                  element(e::Situational, "Pay-To Plan Address Line")),
                segment(300, s::N4, "Pay-To Plan City, State, ZIP Code",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Pay-to Plan City Name"),
                  element(e::Situational, "Pay-to Plan State or Province Code"),
                  element(e::Situational, "Pay-to Plan Postal Zone or ZIP Code"),
                  element(e::Situational, "Country Code"),
                  element(e::NotUsed,     "Location Qualifier"),
                  element(e::NotUsed,     "Location Identifier"),
                  element(e::Situational, "Country Subdivision Code")),
                segment(350, s::REF, "Pay-to Plan Secondary Identification",
                  r::Situational, d::RepeatCount.bounded(1),
                  element(e::Required,    "Reference Identification Qualifier", Codes("2U", "FY", "NF")),
                  element(e::Required,    "Pay-to Plan Secondary Identifier"),
                  element(e::NotUsed,     "Description"),
                  element(e::NotUsed,     "REFERENCE IDENTIFIER")),
                segment(350, s::REF, "Pay-to Plan Tax Identification Number",
                  r::Required, d::RepeatCount.bounded(1),
                  element(e::Required,    "Reference Identification Qualifier", Codes("EI")),
                  element(e::Required,    "Pay-to Plan Tax Identification Number"),
                  element(e::NotUsed,     "Description"),
                  element(e::NotUsed,     "REFERENCE IDENTIFIER"))))),

          d::TableDef.build("Table 2 - Subscriber Detail",
            d::LoopDef.build("2000B SUBSCRIBER HIERARCHICAL LEVEL", d::RepeatCount.unbounded,
              s:: HL.use( 10, r::Required, d::RepeatCount.bounded(1)),
              s::SBR.use( 50, r::Situational, d::RepeatCount.bounded(1)),
              s::PAT.use( 70, r::Situational, d::RepeatCount.bounded(1)),

              d::LoopDef.build("2010BA SUBSCRIBER NAME", d::RepeatCount.bounded(1),
                s::NM1.use(150, r::Required, d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Situational, d::RepeatCount.bounded(1)),
                s:: N4.use(300, r::Required, d::RepeatCount.bounded(1)),
                s::DMG.use(320, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Situational, d::RepeatCount.bounded(1)),
                s::PER.use(400, r::Situational, d::RepeatCount.bounded(1))),

              d::LoopDef.build("2010BB PAYER NAME", d::RepeatCount.bounded(10),
                s::NM1.use(150, r::Required, d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Situational, d::RepeatCount.bounded(2)),
                s:: N4.use(300, r::Required, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Situational, d::RepeatCount.bounded(3)),
                s::REF.use(350, r::Situational, d::RepeatCount.bounded(2))))),

          d::TableDef.build("Table 2 - Patient Detail",
            d::LoopDef.build("2000 PATIENT HIERARCHICAL LEVEL", d::RepeatCount.unbounded,
              s:: HL.use( 10, r::Situational, d::RepeatCount.bounded(1)),
              s::PAT.use( 70, r::Required, d::RepeatCount.bounded(1)),

              d::LoopDef.build("2010CA PATIENT NAME", d::RepeatCount.bounded(1),
                s::NM1.use(150, r::Required, d::RepeatCount.bounded(1)),
                s:: N3.use(250, r::Required, d::RepeatCount.bounded(1)),
                s:: N4.use(300, r::Required, d::RepeatCount.bounded(1)),
                s::DMG.use(320, r::Required, d::RepeatCount.bounded(1)),
                s::REF.use(350, r::Situational, d::RepeatCount.bounded(1)),
                s::PER.use(400, r::Situational, d::RepeatCount.bounded(1))),

              d::LoopDef.build("2300 CLAIM INFORMATION", d::RepeatCount.bounded(100),
                s::CLM.use(1300, r::Required, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(2)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::DTP.use(1350, r::Situational, d::RepeatCount.bounded(1)),
                s::PWK.use(1550, r::Situational, d::RepeatCount.bounded(10)),
                s::CN1.use(1600, r::Situational, d::RepeatCount.bounded(1)),
                s::AMT.use(1750, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s::REF.use(1800, r::Situational, d::RepeatCount.bounded(1)),
                s:: K3.use(1850, r::Situational, d::RepeatCount.bounded(10)),
                s::NTE.use(1900, r::Situational, d::RepeatCount.bounded(1)),
                s::CR1.use(1950, r::Situational, d::RepeatCount.bounded(1)),
                s::CR2.use(2000, r::Situational, d::RepeatCount.bounded(1)),
                s::CRC.use(2200, r::Situational, d::RepeatCount.bounded(3)),
                s::CRC.use(2200, r::Situational, d::RepeatCount.bounded(3)),
                s::CRC.use(2200, r::Situational, d::RepeatCount.bounded(1)),
                s::CRC.use(2200, r::Situational, d::RepeatCount.bounded(1)),
                s:: HI.use(2310, r::Required, d::RepeatCount.bounded(1)),
                s:: HI.use(2310, r::Situational, d::RepeatCount.bounded(1)),
                s:: HI.use(2310, r::Situational, d::RepeatCount.bounded(1)),
                s::HCP.use(2410, r::Situational, d::RepeatCount.bounded(1)),

                d::LoopDef.build("2310A REFERRING PROVIDER NAME", d::RepeatCount.bounded(2),
                  s::NM1.use(2500, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(2710, r::Situational, d::RepeatCount.bounded(3))),

                d::LoopDef.build("2310B RENDERING PROVIDER NAME", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Situational, d::RepeatCount.bounded(1)),
                  s::PRV.use(2550, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(2710, r::Situational, d::RepeatCount.bounded(4))),

                d::LoopDef.build("2310C SERVICE FACILITY LOCATION NAME", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Situational, d::RepeatCount.bounded(1)),
                  s:: N3.use(2650, r::Required, d::RepeatCount.bounded(2)),
                  s:: N4.use(2700, r::Required, d::RepeatCount.bounded(1)),
                  s::REF.use(2710, r::Situational, d::RepeatCount.bounded(3)),
                  s::PER.use(2750, r::Situational, d::RepeatCount.bounded(1))),

                d::LoopDef.build("2310D SUPERVISING PROVIDER NAME", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(2710, r::Situational, d::RepeatCount.bounded(4))),

                d::LoopDef.build("2310E AMBULANCE DROP-OFF LOCATION", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Situational, d::RepeatCount.bounded(1)),
                  s:: N3.use(2650, r::Situational, d::RepeatCount.bounded(2)),
                  s:: N4.use(2700, r::Situational, d::RepeatCount.bounded(1))),

                d::LoopDef.build("2310F AMBULANCE DROP-OFF LOCATION", d::RepeatCount.bounded(1),
                  s::NM1.use(2500, r::Situational, d::RepeatCount.bounded(1)),
                  s:: N3.use(2650, r::Situational, d::RepeatCount.bounded(1)),
                  s:: N4.use(2700, r::Situational, d::RepeatCount.bounded(1))),

                d::LoopDef.build("2320 OTHER SUBSCRIBER INFORMATION", d::RepeatCount.bounded(10),
                  s::SBR.use(2900, r::Situational, d::RepeatCount.bounded(1)),
                  s::CAS.use(2950, r::Situational, d::RepeatCount.bounded(5)),
                  s::AMT.use(3000, r::Situational, d::RepeatCount.bounded(1)),
                  s::AMT.use(3000, r::Situational, d::RepeatCount.bounded(1)),
                  s::AMT.use(3000, r::Situational, d::RepeatCount.bounded(1)),
                  s:: OI.use(3100, r::Required, d::RepeatCount.bounded(1)),
                  s::MOA.use(3200, r::Situational, d::RepeatCount.bounded(1)),

                  d::LoopDef.build("2330A OTHER SUBSCRIBER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Required, d::RepeatCount.bounded(1)),
                    s:: N3.use(3320, r::Situational, d::RepeatCount.bounded(1)),
                    s:: N4.use(3400, r::Required, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Situational, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2330B OTHER PAYER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Required, d::RepeatCount.bounded(1)),
                    s:: N3.use(3320, r::Situational, d::RepeatCount.bounded(1)),
                    s:: N4.use(3400, r::Required, d::RepeatCount.bounded(1)),
                    s::DTP.use(3500, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Situational, d::RepeatCount.bounded(2)),
                    s::REF.use(3550, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Situational, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2330C OTHER PAYER REFERRING PROVIDER", d::RepeatCount.bounded(2),
                    s::NM1.use(3250, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Required, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2330D OTHER PAYER RENDERING PROVIDER", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Required, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2330E OTHER PAYER SERVICE FACILITY LOCATION", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Required, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2330F OTHER PAYER SUPERVISING PROVIDER", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Required, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2330G OTHER PAYER BILLING PROVIDER", d::RepeatCount.bounded(1),
                    s::NM1.use(3250, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(3550, r::Required, d::RepeatCount.bounded(2)))),

                d::LoopDef.build("2400", d::RepeatCount.bounded(50),
                  s:: LX.use(3650, r::Required, d::RepeatCount.bounded(1)),
                  s::SV1.use(3700, r::Required, d::RepeatCount.bounded(1)),
                  s::SV5.use(4000, r::Situational, d::RepeatCount.bounded(1)),
                  s::PWK.use(4200, r::Situational, d::RepeatCount.bounded(10)),
                  s::PWK.use(4200, r::Situational, d::RepeatCount.bounded(1)),
                  s::CR1.use(4250, r::Situational, d::RepeatCount.bounded(1)),
                  s::CR3.use(4350, r::Situational, d::RepeatCount.bounded(1)),
                  s::CRC.use(4500, r::Situational, d::RepeatCount.bounded(3)),
                  s::CRC.use(4500, r::Situational, d::RepeatCount.bounded(1)),
                  s::CRC.use(4500, r::Situational, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Required, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(2)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(1)),
                  s::DTP.use(4550, r::Situational, d::RepeatCount.bounded(1)),
                  s::QTY.use(4600, r::Situational, d::RepeatCount.bounded(1)),
                  s::QTY.use(4600, r::Situational, d::RepeatCount.bounded(1)),
                  s::MEA.use(4620, r::Situational, d::RepeatCount.bounded(5)),
                  s::CN1.use(4650, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(5)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(1)),
                  s::REF.use(4700, r::Situational, d::RepeatCount.bounded(5)),
                  s::AMT.use(4750, r::Situational, d::RepeatCount.bounded(1)),
                  s::AMT.use(4750, r::Situational, d::RepeatCount.bounded(1)),
                  s:: K3.use(4800, r::Situational, d::RepeatCount.bounded(10)),
                  s::NTE.use(4850, r::Situational, d::RepeatCount.bounded(1)),
                  s::NTE.use(4850, r::Situational, d::RepeatCount.bounded(1)),
                  s::PS1.use(4880, r::Situational, d::RepeatCount.bounded(1)),
                  s::HCP.use(4920, r::Situational, d::RepeatCount.bounded(1)),

                  d::LoopDef.build("2410 DRUG IDENTIFICATION", d::RepeatCount.bounded(1),
                    s::LIN.use(4930, r::Situational, d::RepeatCount.bounded(1)),
                    s::CTP.use(4940, r::Required, d::RepeatCount.bounded(1)),
                    s::REF.use(4950, r::Situational, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2420A RENDERING PROVIDER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Situational, d::RepeatCount.bounded(1)),
                    s::PRV.use(5050, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Situational, d::RepeatCount.bounded(20))),

                  d::LoopDef.build("2420B PURCHASED SERVICE PROVIDER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Situational, d::RepeatCount.bounded(20))),

                  d::LoopDef.build("2420C SERVICE FACILITY LOCATION NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Situational, d::RepeatCount.bounded(1)),
                    s:: N3.use(5140, r::Required, d::RepeatCount.bounded(1)),
                    s:: N4.use(5200, r::Required, d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Situational, d::RepeatCount.bounded(3))),

                  d::LoopDef.build("2420D SUPERVISING PROVIDER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Situational, d::RepeatCount.bounded(20))),

                  d::LoopDef.build("2420E ORDERING PROVIDER NAME", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Situational, d::RepeatCount.bounded(1)),
                    s:: N3.use(5140, r::Situational, d::RepeatCount.bounded(1)),
                    s:: N4.use(5200, r::Required, d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Situational, d::RepeatCount.bounded(20)),
                    s::PER.use(5300, r::Situational, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2420F REFERRING PROVIDER NAME", d::RepeatCount.bounded(2),
                    s::NM1.use(5000, r::Situational, d::RepeatCount.bounded(1)),
                    s::REF.use(5250, r::Situational, d::RepeatCount.bounded(20))),

                  d::LoopDef.build("2420G AMBULANCE PICK-UP LOCATION", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Situational, d::RepeatCount.bounded(1)),
                    s:: N3.use(5140, r::Required, d::RepeatCount.bounded(1)),
                    s:: N4.use(5200, r::Required, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2420H AMBULANCE DROP-OFF LOCATION", d::RepeatCount.bounded(1),
                    s::NM1.use(5000, r::Situational, d::RepeatCount.bounded(1)),
                    s:: N3.use(5140, r::Required, d::RepeatCount.bounded(1)),
                    s:: N4.use(5200, r::Required, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2430 LINE ADJUDICATION INFORMATION", d::RepeatCount.bounded(15),
                    s::SVD.use(5400, r::Situational, d::RepeatCount.bounded(1)),
                    s::CAS.use(5450, r::Situational, d::RepeatCount.bounded(5)),
                    s::DTP.use(5500, r::Required, d::RepeatCount.bounded(1)),
                    s::AMT.use(5505, r::Situational, d::RepeatCount.bounded(1))),

                  d::LoopDef.build("2440", d::RepeatCount.unbounded,
                    s:: LQ.use(5510, r::Situational, d::RepeatCount.bounded(1)),
                    s::FRM.use(5520, r::Required, d::RepeatCount.bounded(99))))))))

      end
    end
  end
end
